---
title: "Iouli_plots2"
author: "Daina"
date: "December 17, 2015"
output: html_document
---

```{r}
library(ggplot2)
library(dplyr)
library(scales)
library(data.table)
library(plyr)
```
   
```{r}
# Preprocessing for density chart
raw1 <- read.csv("JMoSp_noLink_ready_for_processing.csv")
str(raw1)
colnames(raw1)
keeps1 <- c("Non_self_referencial_link","citationCount", "dateYear")
link_data1 <- raw1[keeps1]

raw2 <- read.csv("JMoSp_records_ready_for_processing.csv")
keeps2 <- c("Non_self_referencial_link","citationCount", "dateYear")
link_data2 <- raw2[keeps2]

link_data <- rbind(link_data1,link_data2)

colnames(link_data) <- c("Links", "Citations", "Year") 
link_data$Links <- factor(link_data$Links)
target <- c("2007","2008","2009","2010","2011","2012","2013","2014")
sub_link_data <- filter(link_data, Year %in% target)

l2 <- ggplot(sub_link_data, aes(x = Citations, fill = Links)) + 
  geom_density(alpha = .3) +
  facet_grid(Year ~.) +
  scale_fill_manual( values = c("green","blue"))
l2 <- l2 + xlab("Citations") + ylab("Density") + ggtitle("Number of Citations for Papers with and without Links")
l2

ggsave('l2.png', height = 11, width = 8.5)
```

```{r}
# Scatterplot of broken links with two different symbols- all links included (1), curated links removed (2) (each year should = 100%)
# only the percent that are broken

cur_links <- read.csv("JMoSp_records_trustedRepo.csv")
colnames(cur_links)

keeps3 <- c("trustedRepo","StatusOverview", "dateYear")
cur_links <- cur_links[keeps3]
cur_links$dateYear <- factor(cur_links$dateYear)
str(cur_links)
colnames(cur_links) <- c("Trusted", "Status", "Year")

# Only keep the "broken" links
target2 <- c("BROKEN")
broken_cur_links <- filter(cur_links, Status %in% target2)
# Keep just the other two columns
keeps4 <- c("Trusted", "Year")
broken_cur_links <- broken_cur_links[keeps4]

broken_cur_links2 <-ddply(broken_cur_links,.(Trusted,Year), mutate, count1=length(Trusted))
broken_cur_links2 <- unique(broken_cur_links2)
str(broken_cur_links2)
write.csv(broken_cur_links2, "broken_cur_links2.csv") #manually modify table to add back years where "broken" was null
broken_cur_links2 <- read.csv("broken_cur_links2.csv")
broken_cur_links2$Year <- factor(broken_cur_links2$Year)
broken_cur_links2$count1 <- as.numeric(broken_cur_links2$count1)
broken_cur_links2$Trusted <- factor(broken_cur_links2$Trusted)
str(broken_cur_links2)

# plot counts
n <- ggplot(broken_cur_links2, aes(Year, count1, colour=Trusted, shape = Trusted))
n <- n + geom_point(size = 4)
n <- n + xlab("Year") + ylab("Count of the Broken Links") + ggtitle("Broken Links by Year for Trusted and Non-Trusted Repos")
n
ggsave('n.png', height = 8, width = 8.5)

# get percent by factor and add back lables
broken_cur_links3 <- ddply(broken_cur_links2, .(Year), summarise, pct = count1 / sum(count1))
broken_cur_links3$Trusted <- rep(c("FALSE", "TRUE"), 11)
broken_cur_links3

# Plot Percentages
p <- ggplot(broken_cur_links3, aes(Year, pct, colour=Trusted, shape = Trusted))
p <- p + geom_point(size = 4)
p <- p + xlab("Year") + ylab("Percent of the Broken Links") + ggtitle("Broken Links by Year for Trusted and Non-Trusted Repos")
p 
ggsave('p.png', height = 8, width = 8.5)
```
```{r}
#line plot - (ohio state and science direct) vs other (only broken links)
# Plot Percentages as line plot
broken_cur_links3$Trusted <- factor(broken_cur_links3$Trusted)
q <- ggplot(broken_cur_links3, aes(x=Year, y=pct, color = Trusted, group=Trusted))
q <- q + geom_line(size = 1)
q <- q + xlab("Year") + ylab("Percent of the Broken Links") + ggtitle("Broken Links by Year for Trusted and Non-Trusted Repos")
q
ggsave('q.png', height = 8, width = 8.5)
```





